name: Build UNO Q Zephyr Loader

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-venv build-essential \
                              git cmake ninja-build zstd jq rsync

      - name: Bootstrap Zephyr & SDK Toolchains
        run: |
          chmod +x ./extra/bootstrap.sh
          ./extra/bootstrap.sh

      - name: Build Arduino UNO Q Custom Loader
        run: |
          chmod +x ./extra/build.sh
          ./extra/build.sh arduino_uno_q

      - name: Upload Firmware and Variant Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unoq-i2s-firmware
          path: |
            firmware/zephyr-arduino_uno_q_stm32u585xx.elf
            firmware/zephyr-arduino_uno_q_stm32u585xx.bin
            variants/arduino_uno_q_stm32u585xx/syms-dynamic.ld
            variants/arduino_uno_q_stm32u585xx/syms-static.ld
